////LOGIN////
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

///MASTER///
export const STORE_MASTER_DATA = "STORE_MASTER_DATA";

///STUDENT///
export const STORE_STUDENT_DATA = "STORE_STUDENT_DATA";
export const ADD_STUDENT_DATA = "ADD_STUDENT_DATA";
export const DELETE_STUDENT_DATA = "DELETE_STUDENT_DATA";

////FOLLOWUP///
export const STORE_FOLLOWUP_DATA = "STORE_FOLLOWUP_DATA";
export const ADD_FOLLOWUP_FOLLOWUPS = "ADD_FOLLOWUP_FOLLOWUPS";

///TASK///
export const STORE_TASK_DATA = "STORE_TASK_DATA";

/////LOGOUT////
export const LOGOUT = "LOGOUT";
